Добавлена главная страница, мобильный вид
htmlacademy-adaptive/2021107-cat-energy-26 pull request #2
Opened 2022-08-01 18:53 UTC by Cashkacaca

2022-08-02 16:45 UTC, firefoxic requested changes

2022-08-02 16:45 UTC, firefoxic commented on source/index.html
> +			<button class="main-nav__toggle" type="button"><span class="visually-hidden">Открыть меню.</span></button>
У скрытых описаний не нужны точки. Только у `alt` в `img`.
Это была ошибка в критериях первого курса.

2022-08-02 16:45 UTC, firefoxic commented on source/index.html
> +					<h2 class="advantages__title">Функциональное питание для котов</h2>
Какая-то избыточность «Функционального питания для котов» :)

2022-08-02 16:45 UTC, firefoxic commented on source/index.html
> +						<p class="servise__description">Функциональное питание содержит только полезные питательные вещества.</p>
В параграфах тут нет необходимости, текст этот может и в `li` нормально лежать.

2022-08-02 16:45 UTC, firefoxic commented on source/index.html
> +					<p class="example__description example__description--view">Затраты на питание: 15 000 РУБ.</p>
Правильно, что внутрь `dl` включил, ведь это тоже одни из данных программы питания. Только надо тоже не параграфом разметить, а на пару `dt+dd` разбить.  
Тем более что в списке `dl` могут быть только `dt` и `dd` (либо `div` содержащие только `dt` и `dd`).

2022-08-02 16:45 UTC, firefoxic commented on source/index.html
> +					<dd class="example__description">затрачено времени</dd>
`dl` — это список пар ключ/значение. Что из этого всего ключи, и что значения?

2022-08-02 16:45 UTC, firefoxic commented on source/index.html
> +					</svg>
Давай заменим на простой `img`. Вся эта svg-кОтОвасия в разметке нам не пригодится 😸

2022-08-02 16:45 UTC, firefoxic commented on source/index.html
> +						<path fill="#2E368F" d="M30.2 5h-.2l-19.7 2.1v36.2l19.7 11.7 19.7-11.7v-36.2l-19.5-2.1zm17 36.8l-17.2 10.2-17.2-10.2v-14.8l17.1 10.2v1.8l-11.7-7v1.8l11.8 7.1v1.9l-11.8-7v1.8l11.8 7 11.9-7.1v-7.
Лого академии на этом сайте — просто иконка. А иконки не контентные. Добавим её через стили.

2022-08-02 16:45 UTC, firefoxic commented on source/index.html
> +					</li>
Тут опечатка в слове `serviCe`, из-за которой бэм линтер считает, что эти элементы без своего блока.

2022-08-02 16:45 UTC, firefoxic commented on source/index.html
> +						<button class="range__button button--statistics" type="button">стало</button>
У кнопок было/стало модификаторы бэм-блока, а сущность — бэм-элемент. Модификатор должен модифицировать ту сущность, на которой стоит.

2022-08-04 05:53 UTC, firefoxic requested changes

2022-08-04 05:53 UTC, firefoxic commented on source/form.html
> +							<input class="effect__input" type="radio" name="effect" value="slim" checked />
Закрывающий `/` у одиночных тегов в html не нужен.  
Вот в svg без него нельзя.

2022-08-04 05:53 UTC, firefoxic commented on source/form.html
> +							<input class="contacts-buyer__input" type="email" name="email" placeholder="kuklachev@gmail.com" />
У обязательных полей должен быть атрибут `required`.

2022-08-04 05:53 UTC, firefoxic commented on source/form.html
> +			</fieldset>
Когда поле одно — это уже не группа полей, не set of fields. Тут `fieldset` можно смело заменить на `div`, `legend` на `label`, а `textarea` вытащить из нынешнего `label`, который без текста.

2022-08-04 05:53 UTC, firefoxic commented on source/catalog.html
> +						<h3 class="product-card__title">Cat Energy PRO 500 г</h3>
Фото товара — это тоже информация о товаре. А заголовок с названием товара должен озаглавливать всю информацию о нём. А фото должно быть после заголовка.

2022-08-04 05:53 UTC, firefoxic commented on source/catalog.html
> +					</dl>
Если и размечать эти данные списком `dl`, то тогда надо `dt` делать с названием данных, с ключём. А тут одно значение получается как ключ к другому.  
Для рублей то всё просто — это «Цена».  
А вот с предыдущим придётся немного подумать (чтобы и под литры и под упаковки подходило). Как вариант «Форма выпуска».  
Ну и эти `dt` тут получается, что надо скрывать доступно.

2022-08-04 20:20 UTC, Cashkacaca commented on source/catalog.html
> +					</dl>
А если это переделать  списком? Или всё-таки оставить списком: dt-объём упаковки dd- 100 г   dt-цена упаковки dd- 200 руб.  Я в замешательстве какой вариант лучше.

2022-08-05 09:30 UTC, merged